- hosts: localhost
  connection: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: true
        upgrade: true
        state: latest

  tasks:
    - include: tasks/packages.yml

