- hosts: localhost
  connection: localhost
  become: true
  pre_tasks:
    - name: Update repo on Ubuntu
      apt: 
        update_cache: yes
        force_apt_get: yes
    - name: Upgrade Ubuntu
      apt:
        upgrade: dist
        force_apt_get: yes
  tasks:
    - include: tasks/packages.yml

