- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: true
        upgrade: true
        state: latest
#      changed_when: False
  tasks:
    - include: tasks/packages.yml
    - include: tasks/docker.yml

